#!/usr/bin/env bash
## -*- sh-basic-offset: 2 -*-
set -x

if [ ! -d "be-tree" ]; then
    git clone -b 'upkeep/otp-26-include-directory' --single-branch --depth 1 http://github.com/AntoineGagne/be-tree
    cd be-tree
    make NIF=true
fi

